/**
 * ===== DEMO SEED DATA =====
 * All data below is synthetic, for development/demo purposes only.
 * Not sourced from real organizations, real users, or real field surveys.
 * Must be replaced with real data before any production deployment.
 */

export const DEMO_REPORTS = [
  {
    id: "demo-r1",
    title: "Plastic waste accumulation near south bank",
    description: "Large amounts of single-use plastic bags and bottles piled along the southern shore. Appears to have accumulated over several weeks.",
    lat: 12.9716,
    lng: 77.5946,
    locationText: "South Bank, Demo Lake",
    waterBodyName: "Demo Lake",
    pollutionCategory: "plastic" as const,
    manualSeverity: 4,
    aiSeverity: 4,
    status: "open" as const,
    userName: "Demo User A",
    userAvatar: "",
    imageUrl: "",
    createdAt: "2026-03-28T10:30:00Z",
    likes: 12,
    comments: 3,
  },
  {
    id: "demo-r2",
    title: "Construction debris dumped near inlet",
    description: "Broken concrete, tiles, and sand bags deposited near the canal inlet. Blocking water flow partially.",
    lat: 12.9352,
    lng: 77.6245,
    locationText: "North Inlet, Demo Canal",
    waterBodyName: "Demo Canal",
    pollutionCategory: "construction" as const,
    manualSeverity: 3,
    aiSeverity: 3,
    status: "under_review" as const,
    userName: "Demo User B",
    userAvatar: "",
    imageUrl: "",
    createdAt: "2026-03-27T14:15:00Z",
    likes: 8,
    comments: 1,
  },
  {
    id: "demo-r3",
    title: "Sewage overflow observed",
    description: "Dark, foul-smelling water flowing into the pond from a broken pipe on the eastern side.",
    lat: 13.0827,
    lng: 80.2707,
    locationText: "East Shore, Demo Pond",
    waterBodyName: "Demo Pond",
    pollutionCategory: "sewage" as const,
    manualSeverity: 5,
    aiSeverity: 5,
    status: "open" as const,
    userName: "Demo User C",
    userAvatar: "",
    imageUrl: "",
    createdAt: "2026-03-29T08:00:00Z",
    likes: 24,
    comments: 7,
  },
  {
    id: "demo-r4",
    title: "Foam and detergent residue on surface",
    description: "White foam visible across a large section of the lake surface, likely from nearby laundry discharge.",
    lat: 19.076,
    lng: 72.8777,
    locationText: "West Side, Demo Wetland",
    waterBodyName: "Demo Wetland",
    pollutionCategory: "foam" as const,
    manualSeverity: 2,
    aiSeverity: 3,
    status: "action_planned" as const,
    userName: "Demo User D",
    userAvatar: "",
    imageUrl: "",
    createdAt: "2026-03-26T16:45:00Z",
    likes: 5,
    comments: 2,
  },
  {
    id: "demo-r5",
    title: "Mixed litter along walking trail",
    description: "Food wrappers, bottles, and cloth pieces scattered along the path near the river bank.",
    lat: 28.6139,
    lng: 77.209,
    locationText: "Trail Path, Demo River",
    waterBodyName: "Demo River",
    pollutionCategory: "mixed" as const,
    manualSeverity: 3,
    aiSeverity: 2,
    status: "open" as const,
    userName: "Demo User E",
    userAvatar: "",
    imageUrl: "",
    createdAt: "2026-03-30T11:00:00Z",
    likes: 15,
    comments: 4,
  },
];

export const DEMO_POSTS = [
  {
    id: "demo-p1",
    type: "event" as const,
    title: "Cleanup Drive this Sunday — Demo Lake South Bank",
    content: "Join us for a community cleanup! We'll provide gloves, bags, and refreshments. Meeting at the south entrance at 7 AM.",
    userName: "Demo Organizer",
    waterBodyName: "Demo Lake",
    createdAt: "2026-03-29T09:00:00Z",
    likes: 32,
    comments: 8,
    participants: 18,
  },
  {
    id: "demo-p2",
    type: "update" as const,
    title: "Collected 15 bags of plastic today!",
    content: "Our team of 12 volunteers spent 3 hours cleaning the canal bank. Great turnout and visible improvement!",
    userName: "Demo Volunteer Group",
    waterBodyName: "Demo Canal",
    createdAt: "2026-03-28T17:00:00Z",
    likes: 45,
    comments: 6,
    participants: 0,
  },
  {
    id: "demo-p3",
    type: "call_for_help" as const,
    title: "Need 20 volunteers for wetland restoration",
    content: "The wetland area is heavily polluted and we need a coordinated effort. Tools and training will be provided.",
    userName: "Demo Conservation Lead",
    waterBodyName: "Demo Wetland",
    createdAt: "2026-03-27T12:00:00Z",
    likes: 19,
    comments: 11,
    participants: 7,
  },
];

export const DEMO_ORGANIZATIONS = [
  {
    id: "demo-org1",
    name: "Demo Environmental Foundation",
    type: "NGO" as const,
    verified: true,
    focusArea: "Lake conservation & community cleanup",
    areaServed: "Demo City South",
    city: "Demo City",
    state: "Demo State",
    note: "DEMO SEED DATA — not a real organization",
  },
  {
    id: "demo-org2",
    name: "Demo Municipal Water Department",
    type: "government" as const,
    verified: true,
    focusArea: "Water body maintenance & sewage management",
    areaServed: "Demo City",
    city: "Demo City",
    state: "Demo State",
    note: "DEMO SEED DATA — not a real organization",
  },
  {
    id: "demo-org3",
    name: "Demo Youth Conservation Club",
    type: "community" as const,
    verified: false,
    focusArea: "Youth-led cleanup drives and awareness",
    areaServed: "Demo City North",
    city: "Demo City",
    state: "Demo State",
    note: "DEMO SEED DATA — not a real organization",
  },
];

export const POLLUTION_CATEGORIES = [
  { value: "plastic", label: "Plastic", icon: "🧴" },
  { value: "mixed", label: "Mixed Litter", icon: "🗑️" },
  { value: "construction", label: "Construction Waste", icon: "🧱" },
  { value: "sewage", label: "Sewage", icon: "🚰" },
  { value: "foam", label: "Foam / Detergent", icon: "🫧" },
  { value: "organic", label: "Organic / Dead Biomass", icon: "🍂" },
  { value: "ewaste", label: "E-Waste", icon: "🔌" },
  { value: "hazardous", label: "Hazardous-like", icon: "☣️" },
  { value: "cloth", label: "Cloth / Textile", icon: "👕" },
  { value: "glass", label: "Glass", icon: "🫙" },
];

export const SEVERITY_LABELS = [
  { level: 1, label: "Minimal", description: "Minor, isolated litter" },
  { level: 2, label: "Low", description: "Noticeable but contained" },
  { level: 3, label: "Moderate", description: "Significant accumulation" },
  { level: 4, label: "High", description: "Heavy pollution, action needed" },
  { level: 5, label: "Critical", description: "Severe, potential health hazard" },
];

export const DASHBOARD_STATS = {
  totalReports: DEMO_REPORTS.length,
  openReports: DEMO_REPORTS.filter(r => r.status === "open").length,
  resolvedReports: 0,
  totalVolunteers: 47,
  cleanupEvents: DEMO_POSTS.filter(p => p.type === "event").length,
  topWaterBodies: [
    { name: "Demo Lake", reports: 2, avgSeverity: 4 },
    { name: "Demo Pond", reports: 1, avgSeverity: 5 },
    { name: "Demo Canal", reports: 1, avgSeverity: 3 },
    { name: "Demo Wetland", reports: 1, avgSeverity: 2 },
  ],
  note: "All stats computed from demo seed data only",
};
